-- 코드를 입력하세요
SELECT
       TO_CHAR(SALES_DATE, 'YYYY-mm-dd') as SALES_DATE
     , PRODUCT_ID
     , USER_ID
     , SALES_AMOUNT
  FROM ONLINE_SALE
 WHERE TO_CHAR(SALES_DATE, 'YYYY-mm-dd') LIKE '____-03-__'
UNION
SELECT
        TO_CHAR(SALES_DATE, 'YYYY-mm-dd') as SALES_DATE
     , PRODUCT_ID
     , NULL AS USER_ID
     , SALES_AMOUNT
  FROM OFFLINE_SALE
 WHERE TO_CHAR(SALES_DATE, 'YYYY-mm-dd') LIKE '____-03-__'