-- 코드를 입력하세요
SELECT
       MEMBER_ID
     , MEMBER_NAME
     , GENDER
     --, TO_DATE(DATE_OF_BIRTH, 'YYYY-MM-DD') AS 
     , TO_CHAR(DATE_OF_BIRTH, 'YYYY-MM-DD') AS DATE_OF_BIRTH
  FROM MEMBER_PROFILE
 WHERE GENDER = 'W'
   AND TLNO IS NOT NULL
   AND extract(MONTH FROM DATE_OF_BIRTH) = '03'
 ORDER BY MEMBER_ID;